package com.mike.strings;

public class ArrayToCoralReadyArray {

    public static void main(String[] args) {
        // TODO Auto-generated method stub
        String str1 = "CN_OFFLINE_EINK_JD_KINDLE    CN_OFFLINE_EINK_JD_PAPERWHITE   CN_OFFLINE_EINK_JD_SIGNATURE    CN_OFFLINE_EINK_TMALL_SIGNATURE CN_ONLINE_EINK_KINDLE   CN_ONLINE_EINK_SIGNATURE    DE_OFFLINE_AUCC DE_ONLINE_TABLET_KET    DE_ONLINE_TABLET_NON_KET    UK_OFFLINE_TABLET_KET_ARGOS UK_OFFLINE_TABLET_KET_NON_ARGOS UK_ONLINE_TABLET_KET    UK_ONLINE_TABLET_NON_KET    US_OFFLINE_AUCC_BBY US_OFFLINE_EINK US_OFFLINE_TABLET_KET   US_OFFLINE_TABLET_NON_KET   US_ONLINE_TABLET_NON_KET";
        String str2 = str1.replaceAll(" +", "\",\"");
        String str3 = "\"" + str2 + "\"";
        System.out.println(str3);
        
        //CN_BRDCST_TABLET_20170928T1458  CN_OFFLINE_TABLET_20170928T1457 CN_ONLINE_TABLET_20170928T1459  DE_BRDCST_AuCC_20160527T1417    DE_EDUENT_TABLET_20170928T1501  ES_BRDCST_TABLET_20170928T1502  FR_BRDCST_TABLET_20170928T1503  FR_OFFLINE_TABLET_20170928T1504 US_OFFLINE_ViCC_PIE_Other_20180319T1506 US_ONLINE_AUCC_SAPPHIRE_20180727T0350
        //415 287 285 410 454 419 417 291 570 795
        //CN_BRDCST_TABLET    CN_OFFLINE_TABLET   CN_ONLINE_TABLET    DE_BRDCST_AuCC  DE_EDUENT_TABLET    ES_BRDCST_TABLET    FR_BRDCST_TABLET    FR_OFFLINE_TABLET   US_OFFLINE_ViCC_PIE_Other   US_ONLINE_AUCC_SAPPHIRE
        
        //System.out.println("-" + Joiner.on(",").join(ImmutableList.of()) + "-");
        //System.out.println("-" + Joiner.on(",").join(null) + "-");
        //System.out.println("-" + StringUtils.join(ImmutableList.of()) + "-");
    }
}
